### ISSUE TITLE
Task 1: Implement traditional trading strategies

### ISSUE THREAD

**Issue by Declan-Lovelock** [Declan-Lovelock/ProfitPilot#1]
### Task 1: Implement traditional trading strategies

- [ ] Research and implement selected traditional trading strategies.
- [ ] Create Python scripts to test each strategy individually on paper (demo) accounts.
- [ ] Assess and visualize the performance of each strategy.

*Consideration*: Ensure you understand the underlying principles of each strategy to select the most appropriate ones for your project.

**Tags**: `trading-strategies`, `implementation`
